import Link from "next/link";

export default function HomePage() {
  return (
    <main className="min-h-screen bg-white flex flex-col justify-center items-center px-4">
        This is the 'Create' page<br></br>
        it is a work in progress<br></br>
        
        TODO:<br></br>
        add UI elements to select stocks(comma separated list? A button for All?)<br></br>
            - filter out stocks based on current price or volume<br></br>

        add UI elements to select earnings reports(date, eps, pre-earnings price change, etc)<br></br>

        add UI elements to create visualizations. <br></br>
            - just a simple bar graph to start.<br></br>
                -y-axis: user can choose a property, or 2 properties plus an operator(e.g. day+5 - day+1)<br></br>
                -x-axis: user can select # of buckets, and ranges will be autogenerated evenly.<br></br>

                OR<br></br>

                -x-axis: user can select fields, e.g. day+1,2,3,etc. Can also apply operators(e.g. subtract close-1 to get price change after ER)<br></br>
                -y-axis: user can select close/open/high/low/volume corresponding to each of those days<br></br>


    </main> 
  );
}
