import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="w-full bg-white flex py-3 px-10 justify-end"> 
          <a href="/login" className="px-4">Login</a> 
          <a href="/login" className="px-4">Sign Up</a> 
        </div>
        {children}
      </body>
    </html>
  );
}
